version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    expose:
      - 5432
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDB}
  flask:
    image: webapp-flask
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/website"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      PYTHONPATH: "/website/"
    ports:
      - "6001:6001"

networks:
  app-network:
    driver: bridge